In [1]:
%cd ../
%matplotlib inline

/home/eli/AnacondaProjects/HTFATorch


In [2]:
import logging
import numpy as np
import htfa_torch.htfa as HTFA
import htfa_torch.niidb as niidb
import htfa_torch.utils as utils

In [3]:
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

In [4]:
synthetic_db = niidb.FMriActivationsDb('data/synthetic_data.db',
                                       mask='data/synthetic_data/nifti_files/wholebrain.nii.gz')

In [5]:
htfa = HTFA.HierarchicalTopographicFactorAnalysis(list(synthetic_db.all()), mask='data/synthetic_data/nifti_files/wholebrain.nii.gz', num_factors=3)

10/02/2019 18:15:27 Loading Nifti image data/synthetic_data/nifti_files/subject_10_task_1_stimulus_1.nii with mask data/synthetic_data/nifti_files/wholebrain.nii.gz (zscore=False, smooth=None)
10/02/2019 18:15:27 Loading Nifti image data/synthetic_data/nifti_files/subject_10_task_1_stimulus_10.nii with mask data/synthetic_data/nifti_files/wholebrain.nii.gz (zscore=False, smooth=None)
10/02/2019 18:15:27 Loading Nifti image data/synthetic_data/nifti_files/subject_10_task_1_stimulus_11.nii with mask data/synthetic_data/nifti_files/wholebrain.nii.gz (zscore=False, smooth=None)
10/02/2019 18:15:27 Loading Nifti image data/synthetic_data/nifti_files/subject_10_task_1_stimulus_12.nii with mask data/synthetic_data/nifti_files/wholebrain.nii.gz (zscore=False, smooth=None)
10/02/2019 18:15:28 Loading Nifti image data/synthetic_data/nifti_files/subject_10_task_1_stimulus_13.nii with mask data/synthetic_data/nifti_files/wholebrain.nii.gz (zscore=False, smooth=None)
10/02/2019 18:15:28 Loading Nif

In [6]:
losses = htfa.train(num_steps=1000, learning_rate=1e-1, log_level=logging.INFO, num_particles=1,
                    batch_size=300, use_cuda=True, blocks_batch_size=9, checkpoint_steps=200,
                    blocks_filter=synthetic_db.inference_filter(training=True))

10/02/2019 18:17:14 [Epoch 1] (8198ms) Posterior free-energy 2.41544736e+08
10/02/2019 18:17:14 Saving checkpoint...
10/02/2019 18:17:22 [Epoch 2] (7912ms) Posterior free-energy 2.22256384e+08
10/02/2019 18:17:30 [Epoch 3] (8014ms) Posterior free-energy 2.03908752e+08
10/02/2019 18:17:38 [Epoch 4] (8177ms) Posterior free-energy 1.96820544e+08
10/02/2019 18:17:46 [Epoch 5] (7805ms) Posterior free-energy 1.92506816e+08
10/02/2019 18:17:54 [Epoch 6] (7716ms) Posterior free-energy 1.90848912e+08
10/02/2019 18:18:02 [Epoch 7] (8098ms) Posterior free-energy 1.90339824e+08
10/02/2019 18:18:10 [Epoch 8] (7722ms) Posterior free-energy 1.89406320e+08
10/02/2019 18:18:18 [Epoch 9] (7799ms) Posterior free-energy 1.89278752e+08
10/02/2019 18:18:26 [Epoch 10] (8063ms) Posterior free-energy 1.89005120e+08
10/02/2019 18:18:34 [Epoch 11] (8121ms) Posterior free-energy 1.88888288e+08
10/02/2019 18:18:42 [Epoch 12] (8010ms) Posterior free-energy 1.88870400e+08
10/02/2019 18:18:50 [Epoch 13] (7696ms) Post

In [7]:
utils.plot_losses(losses)

In [8]:
losses = htfa.train(num_steps=1000, learning_rate=1e-1, log_level=logging.INFO, num_particles=1,
                    batch_size=300, use_cuda=True, blocks_batch_size=9, checkpoint_steps=200,
                    train_globals=False, blocks_filter=synthetic_db.inference_filter(training=False))

10/02/2019 20:18:20 [Epoch 1] (194ms) Posterior free-energy 5.92860900e+06
10/02/2019 20:18:20 Saving checkpoint...
10/02/2019 20:18:20 [Epoch 2] (182ms) Posterior free-energy 5.57163500e+06
10/02/2019 20:18:21 [Epoch 3] (173ms) Posterior free-energy 5.37244750e+06
10/02/2019 20:18:21 [Epoch 4] (174ms) Posterior free-energy 5.15329100e+06
10/02/2019 20:18:21 [Epoch 5] (175ms) Posterior free-energy 5.15494850e+06
10/02/2019 20:18:21 [Epoch 6] (173ms) Posterior free-energy 4.96858400e+06
10/02/2019 20:18:21 [Epoch 7] (174ms) Posterior free-energy 5.03502900e+06
10/02/2019 20:18:21 [Epoch 8] (173ms) Posterior free-energy 4.90726650e+06
10/02/2019 20:18:22 [Epoch 9] (175ms) Posterior free-energy 4.81856350e+06
10/02/2019 20:18:22 [Epoch 10] (173ms) Posterior free-energy 4.79103350e+06
10/02/2019 20:18:22 [Epoch 11] (174ms) Posterior free-energy 4.80507900e+06
10/02/2019 20:18:22 [Epoch 12] (181ms) Posterior free-energy 4.79131050e+06
10/02/2019 20:18:22 [Epoch 13] (178ms) Posterior free-en

In [9]:
utils.plot_losses(losses)

In [14]:
for b in np.random.choice(range(htfa.num_blocks), 5):
    htfa.plot_factor_centers(b)
    htfa.plot_original_brain(b)
    htfa.plot_reconstruction(b)
    print(htfa.results(b))

10/03/2019 10:44:39 Reconstruction Error (Frobenius Norm): 3.22142670e+02 out of 3.22176788e+02


{'factors': tensor([[3.1194e-34, 9.6959e-28, 8.3475e-23,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [4.5963e-37, 1.0202e-35, 9.7267e-35,  ..., 2.6462e-17, 4.6540e-17,
         3.5158e-17]]), 'factor_centers': tensor([[ 39.7410, -40.3976,  21.3474],
        [-35.5983, -42.4710,  20.4794],
        [  3.4806,  27.1661,  17.3449]]), 'factor_log_widths': tensor([3.5749, 2.6599, 5.0203]), 'weights': tensor([[ 0.1130,  1.0785, -0.2280],
        [-0.4923,  1.8878,  0.1656],
        [ 1.0541, -1.0144,  0.4306],
        [-0.7775,  1.0534, -0.3143],
        [ 0.3774, -0.0040,  0.1601],
        [ 0.4409,  1.1175,  0.1791],
        [ 0.1698,  1.3941, -0.3277],
        [-0.0804, -1.4853,  0.4756],
        [ 0.4888,  1.3646,  0.0276],
        [ 0.3027, -1.0095, -0.0580],
        [ 0.4817,  1.5755,  0.4022],
        [-0.2255, -0.4186,  0.0348],
        [-0.4503,  1.9631,  0.2799],
        

10/03/2019 10:46:47 Reconstruction Error (Frobenius Norm): 3.23478699e+02 out of 3.23555817e+02


{'factors': tensor([[1.4225e-14, 8.0545e-12, 1.0213e-09,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 6.1768e-14, 1.7226e-13,
         1.7633e-13],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]]), 'factor_centers': tensor([[ 40.7424, -40.3757,  21.8894],
        [-38.9523, -42.6487,  20.1863],
        [  4.0476,  28.0574,  17.7039]]), 'factor_log_widths': tensor([4.4490, 4.8498, 3.8685]), 'weights': tensor([[-0.1509, -0.6274,  0.0281],
        [ 0.0564,  0.0464,  0.2141],
        [-0.2434, -0.3015,  0.5063],
        [ 0.4934, -0.1080,  0.1141],
        [ 0.1715,  0.3954,  0.4385],
        [-0.1156, -0.3057, -0.5505],
        [-0.0386, -0.2834,  0.2673],
        [ 0.1198,  0.6002,  0.5193],
        [ 0.1668,  0.6574,  0.3095],
        [ 0.2068,  0.7272,  0.4221],
        [ 0.1010, -0.1494,  1.2630],
        [ 0.1780, -0.0685,  0.0773],
        [-0.8268, -0.3687,  0.5799],
        

10/03/2019 10:48:53 Reconstruction Error (Frobenius Norm): 3.20020294e+02 out of 3.20217102e+02


{'factors': tensor([[1.8709e-09, 7.1861e-08, 1.0778e-06,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.0053e-25, 4.4663e-24,
         1.0216e-23],
        [2.9007e-43, 1.1318e-41, 1.6652e-40,  ..., 1.0907e-19, 2.2836e-19,
         1.8036e-19]]), 'factor_centers': tensor([[ 35.8067, -46.9893,  19.0367],
        [-43.2829, -37.5631,  22.9084],
        [  2.9579,  27.5611,  18.0637]]), 'factor_log_widths': tensor([4.9135, 4.0296, 4.8774]), 'weights': tensor([[ 0.0718, -0.9848,  0.0161],
        [ 0.0018, -0.9079, -0.1325],
        [-0.1783, -0.6261, -0.4260],
        [ 0.7383, -1.1321, -0.5291],
        [ 0.3053, -1.2396, -0.2271],
        [ 0.2509, -1.0251, -0.1142],
        [ 0.1628, -0.6498,  0.1716],
        [-0.2671, -0.9586, -0.4705],
        [ 0.4467, -1.2426,  0.2194],
        [-0.4756, -1.1749,  0.0096],
        [ 0.3184, -1.1770, -0.3301],
        [-0.1505, -1.2013,  0.0166],
        [ 0.3288, -0.9812, -0.0995],
        

10/03/2019 10:51:00 Reconstruction Error (Frobenius Norm): 3.19024597e+02 out of 3.20246552e+02


{'factors': tensor([[1.3079e-04, 7.8907e-04, 3.2513e-03,  ..., 9.6497e-21, 1.8547e-20,
         2.4346e-20],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 4.0954e-22, 3.4407e-21,
         4.5248e-21],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]]), 'factor_centers': tensor([[ 45.3870, -32.9406,  25.7087],
        [-40.9658, -38.8084,  21.1814],
        [  3.7924,  27.5641,  18.3524]]), 'factor_log_widths': tensor([5.8162, 4.2344, 3.8928]), 'weights': tensor([[-1.1807, -0.3952, -0.0316],
        [-1.2653,  0.0528, -0.2302],
        [-1.0459, -0.0632,  1.1849],
        [-1.2569, -0.2132,  0.1892],
        [-1.2187, -0.4942,  0.1266],
        [-1.3675,  0.1105,  0.9808],
        [-1.3003,  0.0023, -0.4647],
        [-1.2351,  0.1497, -0.7711],
        [-1.1927, -0.1026, -0.0885],
        [-1.1616,  0.7232, -0.3465],
        [-1.1342,  0.7252,  0.3268],
        [-1.3263,  0.7751,  0.5503],
        [-1.3661,  0.1010, -0.1987],
        

10/03/2019 10:53:04 Reconstruction Error (Frobenius Norm): 3.20546600e+02 out of 3.23989075e+02


{'factors': tensor([[1.6973e-05, 1.4984e-04, 8.3682e-04,  ..., 1.8086e-24, 4.0416e-24,
         5.7130e-24],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 1.8635e-13, 5.0897e-13,
         5.0235e-13],
        [1.9678e-36, 4.5381e-35, 4.6072e-34,  ..., 1.0577e-16, 2.0815e-16,
         1.8034e-16]]), 'factor_centers': tensor([[ 44.2686, -33.5521,  26.0459],
        [-39.6631, -41.2276,  19.8972],
        [  3.0172,  27.1909,  18.6017]]), 'factor_log_widths': tensor([5.6330, 4.8344, 5.0500]), 'weights': tensor([[ 0.0761,  0.1379, -0.0170],
        [ 1.7035,  0.0322, -0.4046],
        [ 0.2710,  0.2495,  0.0511],
        [ 1.6635, -0.3521,  0.2769],
        [ 1.3451, -0.2412,  0.2328],
        [ 0.5363, -0.0251, -0.7532],
        [ 1.8433,  0.2414, -0.4210],
        [ 1.4500,  0.3378, -0.2979],
        [ 1.7701,  0.3827,  0.0786],
        [ 1.5967,  0.4158,  0.3381],
        [ 1.9704,  0.4733,  0.2547],
        [ 1.8833, -0.1917,  0.1407],
        [ 1.1863,  0.0308, -0.2746],
        

In [11]:
def task_rest_labeler(task):
    if 'rest' in str(task):
        return 'Rest'
    else:
        return 'Task %s' % task

In [12]:
htfa.average_reconstruction_error(weighted=False)

10/03/2019 10:42:05 Average reconstruction error (MSE): 3.19600399e+02 +/- 1.65710302e+00
10/03/2019 10:42:05 Average data norm (Euclidean): 3.20555643e+02 +/- 2.01751855e+00
10/03/2019 10:42:05 Percent average reconstruction error: 99.703801 +/- 4.80072701e-01


(array([319.07162476, 317.21881104, 319.32830811, ..., 323.15130615,
        319.31295776, 319.37167358]),
 array([319.70812988, 318.53671265, 320.64831543, ..., 323.17349243,
        323.63345337, 323.11935425]),
 array([0.99800911, 0.99586264, 0.99588332, ..., 0.99993135, 0.98665003,
        0.98840156]))

In [13]:
htfa.free_energy(num_particles=1, batch_size=300, use_cuda=True, blocks_batch_size=20,
                 blocks_filter=synthetic_db.inference_filter(training=False))

[[4235901.5, -4219660.5, 16241.111328125],
 [4708929.5, -2.3025851249694824, 18129.458984375]]